# Copyright (c) The dgc.network
# SPDX-License-Identifier: Apache-2.0

[workspace]

members = [
    "cli",
    "contracts/pike",
    "contracts/product",
    "contracts/schema",
    "contracts/track_and_trace",
    "daemon",
    "sdk"
]
