# Copyright (c) The dgc.network
# SPDX-License-Identifier: Apache-2.0

name: dgc_platform_product
version: '0.1.0'
wasm: /tmp/dgc-platform-product-tp.wasm
inputs:
  - '621dee01'
  - '621dee02'
  - 'cad11d'
outputs:
  - '621dee02'
