# Copyright (c) The dgc.network
# SPDX-License-Identifier: Apache-2.0

version: "3.6"

services:
  grid_tests:
    build:
      context: ../..
      dockerfile: docker/tests
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: dgc-platform:tests
    volumes:
      - ../..:/project/dgc-platform
    command: run_unit_tests
