# Copyright (c) The dgc.network
# SPDX-License-Identifier: Apache-2.0

---
alpha:
  node_id: alpha-node-000
  metadata:
    gameroom/first-name: alice
    gameroom/organization: Alpha
beta:
  node_id: beta-node-000
  metadata:
    gameroom/first-name: bob
    gameroom/organization: Beta
gamma:
  node_id: gamma-node-000
  metadata:
    gameroom/first-name: grace
    gameroom/organization: Gamma
