# Copyright (c) The dgc.network
# SPDX-License-Identifier: Apache-2.0

- identity: 'alpha-node-000'
  endpoint: 'tcps://splinterd-alpha:8044'
  display_name: 'Alpha - Node 0'
  metadata:
    organization: 'Alpha'
- identity: 'beta-node-000'
  endpoint: 'tcps://splinterd-beta:8044'
  display_name: 'Beta - Node 0'
  metadata:
    organization: 'Beta'
- identity: 'gamma-node-000'
  endpoint: 'tcps://splinterd-gamma:8044'
  display_name: 'Gamma - Node 0'
  metadata:
    organization: 'Gamma'
