# Copyright (c) The dgc.network
# SPDX-License-Identifier: Apache-2.0

name: dgc_platform_schema
version: '0.1.0'
wasm: /tmp/dgc-platform-schema-tp.wasm
inputs:
  - '621dee01'
  - 'cad11d'
outputs:
  - '621dee01'
